version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    image: postgres


  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catelog/Catelog.API/Dockerfile

volumes:
  postgres_catalog:

